### ISSUE TITLE
O2Auth for registration page

### ISSUE THREAD

**Issue by Vonuki** [Vonuki/easyqueue#26]
https://github.com/yiisoft/yii2-authclient/blob/master/docs/guide-ru/installation.md

**Comment by ignik86** [comment]
попробовал локально все работает. Коммитить не буду так как все начнут ко мне на роутер ломиться)) так же нужно было внести изменения в исходниках в папке vendor которая в  gitignore. Чтобы можно было ставить c composer нужно добавить зависимость в json. Вообщем нужно разворачивать на хостинге локально уже не катит.
